// Shared creative generation adapter — video + image via a Higgsfield-style HTTP
// API. Availability-checked like every platform wrapper: no key → { available:false }
// and callers degrade to manual production packs. CREATIVE_GEN_DRY_RUN=1 exercises
// the full path without spending provider credits. Media files are NEVER written
// into the repo — only URLs/metadata are stored.
const env = (k) => process.env[k]?.trim() || null;

const API_BASE = () => env("HIGGSFIELD_API_BASE") || "https://platform.higgsfield.ai/v1";
const POLL_TRIES = 6;
const POLL_DELAY_MS = 5000;

export function providerFor(assetType) {
  return assetType === "image"
    ? env("IMAGE_GEN_PROVIDER") || "higgsfield"
    : env("VIDEO_GEN_PROVIDER") || "higgsfield";
}

export function isDryRun() {
  return ["1", "true", "yes"].includes(String(env("CREATIVE_GEN_DRY_RUN") || "").toLowerCase());
}

export function isAvailable() {
  return !!env("HIGGSFIELD_API_KEY");
}

async function jfetch(url, opts = {}) {
  const res = await fetch(url, {
    ...opts,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env("HIGGSFIELD_API_KEY")}`,
      ...(opts.headers || {}),
    },
  });
  const text = await res.text();
  let body;
  try { body = JSON.parse(text); } catch { body = { raw: text.slice(0, 500) }; }
  if (!res.ok) throw new Error(`${res.status} ${String(body?.message || body?.error || res.statusText).slice(0, 300)}`);
  return body;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function submitAndPoll(endpoint, payload, assetType) {
  const job = await jfetch(`${API_BASE()}${endpoint}`, { method: "POST", body: JSON.stringify(payload) });
  const jobId = job?.id || job?.job_id || job?.data?.id;
  if (!jobId) throw new Error("provider returned no job id");
  for (let i = 0; i < POLL_TRIES; i++) {
    await sleep(POLL_DELAY_MS);
    const st = await jfetch(`${API_BASE()}${endpoint}/${jobId}`, { method: "GET" });
    const status = String(st?.status || st?.data?.status || "").toLowerCase();
    const result = st?.result || st?.data?.result || st;
    if (["completed", "succeeded", "success", "done"].includes(status)) {
      return {
        available: true,
        status: "generated",
        provider_job_id: String(jobId),
        preview_url: result?.preview_url || result?.thumbnail_url || null,
        media_url: result?.url || result?.video_url || result?.image_url || result?.media_url || null,
        thumbnail_url: result?.thumbnail_url || null,
        notes: `generated by ${providerFor(assetType)}`,
      };
    }
    if (["failed", "error", "cancelled"].includes(status)) {
      return { available: true, status: "failed", provider_job_id: String(jobId), media_url: null, notes: String(st?.error || "provider job failed").slice(0, 200) };
    }
  }
  // Long renders: hand the job id back — a later run or human can collect the result.
  return { available: true, status: "pending", provider_job_id: String(jobId), media_url: null, notes: "job still rendering — collect via provider dashboard or next run" };
}

function dryRunResult(assetType, prompt) {
  return {
    available: true,
    status: "dry_run",
    provider_job_id: `dry-${Date.now()}`,
    preview_url: null,
    media_url: null,
    thumbnail_url: null,
    notes: `DRY RUN (${providerFor(assetType)}) — no provider call. prompt: ${String(prompt).slice(0, 120)}…`,
  };
}

/**
 * Generate a video. referenceAssets: approved product image URLs (product fidelity).
 * Returns { available, status, provider_job_id, preview_url, media_url, thumbnail_url, notes }.
 */
export async function generateVideo({ prompt, negativePrompt = "", aspectRatio = "9:16", duration = 8, referenceAssets = [] }) {
  if (isDryRun()) return dryRunResult("video", prompt);
  if (!isAvailable()) return { available: false, status: "manual", media_url: null, notes: "no HIGGSFIELD_API_KEY — production pack is manual-film/manual-generate" };
  return submitAndPoll("/text2video", {
    prompt,
    negative_prompt: negativePrompt,
    aspect_ratio: aspectRatio,
    duration,
    reference_images: referenceAssets.map((a) => (typeof a === "string" ? a : a.url)).filter(Boolean),
  }, "video");
}

/** Generate a still image. Same contract as generateVideo. */
export async function generateImage({ prompt, negativePrompt = "", aspectRatio = "1:1", referenceAssets = [] }) {
  if (isDryRun()) return dryRunResult("image", prompt);
  if (!isAvailable()) return { available: false, status: "manual", media_url: null, notes: "no HIGGSFIELD_API_KEY — image brief is manual-shoot/manual-generate" };
  return submitAndPoll("/text2image", {
    prompt,
    negative_prompt: negativePrompt,
    aspect_ratio: aspectRatio,
    reference_images: referenceAssets.map((a) => (typeof a === "string" ? a : a.url)).filter(Boolean),
  }, "image");
}
